### ISSUE TITLE
В 2021.1 при установке нет доступных пакетов

### ISSUE THREAD

**Issue by artbear** [YanSergey/edt.externalDesignerLauncher#1]
![image](https://user-images.githubusercontent.com/2920817/109546623-843dc800-7adb-11eb-9147-5718b327a93d.png)

**Comment by YanSergey** [comment]
Снятие флага "Группировать элементы по категории" не помогает?

**Comment by YanSergey** [comment]
Проверил на EDT 2021.1 - снятие флага помогает.
Дополню этим инструкцию по установке.

**Comment by artbear** [comment]
Да, без указания флага работает.
Спасибо. Закрываю.
